version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    ports:
      - "5002:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - timescaledb_data:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  timescaledb_data:
  qdrant_data: 